apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: presto-coordinator
  namespace: telco-datastorage-mvp
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: ocs-external-storagecluster-ceph-rbd
