apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: hivemr3
  name: workdir-pvc
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Mi
