apiVersion: v1
kind: Service
metadata:
  namespace: sparkmr3
  name: prometheus
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 9890
    targetPort: 9890
  selector:
    sparkmr3_aux: prometheus
  externalIPs:
  - 10.1.91.10
