apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: sparkmr3
  name: worker-role
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get"]
