apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: https://github.com/Swapnil231996/argo.git
    targetRevision: branch55
    path: Prometheus
  destination: 
    server:  https://kubernetes.default.svc
    namespace: key
    

    
