apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nifi
  name: nifi
  namespace: telco-webapplications-mvp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nifi
  template:
    metadata:
      labels:
        app: nifi
    spec:
      securityContext:
        runAsUser: 1000
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/telco-webapplications-mvp/nifi
        imagePullPolicy: Always
        name: nifi
        env:
        - name: NIFI_WEB_PROXY_HOST
          value: nifi-telco-webapplications-mvp.apps.mvp.telcostackmvp.br.telefonica.com
        - name: SINGLE_USER_CREDENTIALS_USERNAME
          value: admin
        - name: SINGLE_USER_CREDENTIALS_PASSWORD
          value: admin1234567
        ports:
        - containerPort: 8443
        volumeMounts:
        - mountPath: /nifi-storage
          name: nifi-storage
      volumes:
      - name: nifi-storage
        persistentVolumeClaim:
          claimName: nifi-storage
