apiVersion: v1
kind: PersistentVolume
metadata:
  name: workdir-pv-ats
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: "10.1.91.17"
    path: "/work/nfs/ats"
