apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default

  source: 
    repoURL: ${repoURL}
    targetRevision: master
    path: Jenkins
  destination: 
    server: ${server}
    namespace: key    
    

    
