apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default

  source:
    repoURL: ${repoURL}
    #repoURL: https://github.com/sagarkivale101/argoCD_test1.git
    targetRevision: HEAD
    path: Jenkins
  destination: 
    server: ${server}
    namespace: key
    
  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
