apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default

  source: https://neil596@bitbucket.org/inilesh/gessa-tools-setup.git
    repoURL: 
    targetRevision: master
    path: Jenkins
  destination: 
    server: "https://kubernetes.default.svc"
    namespace: key    
    

    
