apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-deploy
  labels:
    app: nodejs-app
  annotations:
spec:
  selector:
    matchLabels:
      app: nodejs-app
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
      - name: nodejs-app
        image: aimvector/nodejs:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 0
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          successThreshold: 3
        volumeMounts:
          - name: nodejs-app-vol
            mountPath: /var/nodejs-deploy_home 
      volumes:
        - name: nodejs-app-vol
          persistentVolumeClaim:
            claimName: nodejs-deploy-pvc       