apiVersion: v1
kind: Service
metadata:
  namespace: hivemr3
  name: timelineserver
spec:
  type: LoadBalancer
  ports:
  - name: ats-http
    protocol: TCP
    port: {{ .Values.ats.httpPort }}
    targetPort: 8188
  - name: ats-https
    protocol: TCP
    port: {{ .Values.ats.httpsPort }}
    targetPort: 8190
  selector:
    hivemr3_app: ats
  externalIPs:
  - {{ .Values.ats.externalIp }}
