apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "graph-arangodb"
spec:
  mode: Cluster
  environment: Development
  agents:
    count: 1
    args:
      - --log.level=debug
    resources:
      requests:
        storage: 10Gi
      limits:
        cpu: 2
        memory: 4Gi
    storageClassName: ocs-external-storagecluster-ceph-rbd
  dbservers:
    count: 3
    resources:
      requests:
        storage: 150Gi
      limits:
        cpu: 4
        memory: 16Gi
    storageClassName: ocs-external-storagecluster-ceph-rbd
  coordinators:
    count: 2
    resources:
      limits:
        cpu: 2
        memory: 4Gi
  image: "arangodb/arangodb:3.6.5"
