apiVersion: apps/v1
kind: StatefulSet
metadata:
 name: mongo-gessa
 namespace: gessa
spec:
 serviceName: "mongo-gessa"
 selector:
  matchLabels:
   role: mongo-gessa  
 replicas: 2
 template:
  metadata:
   labels:
    role: mongo-gessa
    environment: test
  spec:
   terminationGracePeriodSeconds: 10
   volumes:
   - name: mongo-pv-storage
     persistentVolumeClaim:
      claimName: mongo-pvc-gessa
   containers:
   - name: mongo
     image: mongo
     env:
       - name: MONGO_INITDB_ROOT_USERNAME
         value: mongoadmin
       - name: MONGO_INITDB_ROOT_PASSWORD
         value: iauro100
     ports:
      - containerPort: 27017
     volumeMounts:
      - name: mongo-pv-storage
        mountPath: /data/db
 volumeClaimTemplates:
  - metadata:
      name: mongo-pv-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 2Gi
