---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    labels:
        app: influxdb
    name: influxdb
    # namespace: telco-datastorage-mvp
spec:
    replicas: 1
    selector:
        matchLabels:
            app: influxdb
    serviceName: influxdb
    template:
        metadata:
            labels:
                app: influxdb
        spec:
            containers:
              - image: influxdb:2.0.6
                name: influxdb
                ports:
                  - containerPort: 8086
                    name: influxdb
                resources:
                  requests:
                    memory: "500Mi"
                    cpu: "200m"
                  limits:
                    memory: "1000Mi"
                    cpu: "500m" 
                readinessProbe:
                    exec:
                      command:
                        - /bin/bash
                    initialDelaySeconds: 10
                    periodSeconds: 25
                livenessProbe:
                    exec:
                      command:
                        - /bin/bash
                    initialDelaySeconds: 10
                    periodSeconds: 25     
                volumeMounts:
                  - mountPath: /var/lib/influxdb2
                    name: data
    volumeClaimTemplates:
      - metadata:
            name: data
        spec:
            accessModes:
              - ReadWriteOnce
            resources:
                requests:
                    storage: 5Gi
    






